---
format:
  html:
    embed-resources: true
engine: knitr
---

{{< include _learning_goals/learning_goals.qmd >}}

{{< include _introduction/business_challenge.qmd >}}


<!-- BEGIN INSERT:prepare-header -->
## Prepare these Exercises before Class 

Prepare these exercises before coming to class. Plan to spend 45 minutes on these exercises.

::: {.callout-important title = "Switch on the `eval` flag when you want to evaluate code!"}
In the R code chunks below we have provided starter code for you to work from.
We have set the key `eval` to the value `false` so that they are not run because they have syntax such as `YOUR_VALUE_HERE` which would generate errors.

Switch the `eval` value to `true` when you want the R code within a chunk to be run when you compile your document.
:::

<!-- END INSERT:prepare-header -->

{{< include _questions/question_01.qmd >}}

{{< include _questions/question_02.qmd >}}

{{< include _questions/question_03.qmd >}}

{{< include _questions/question_04.qmd >}}


<!-- BEGIN INSERT:inclass-header -->
## In-Class Exercises

You will discuss these exercises in class with your peers in small groups and with your tutor. These exercises build from the exercises you have prepared above, you will get the most value from the class if you have completed those above before coming to class.
<!-- END INSERT:inclass-header -->


{{< include _questions/question_05.qmd >}} 

{{< include _questions/question_06.qmd >}} 

{{< include _questions/question_07.qmd >}} 

{{< include _questions/question_08.qmd >}} 
